### ISSUE TITLE
shape: how to see shaped text?

### ISSUE THREAD

**Issue by rajeeshknambiar** [yeslogic/allsorts-tools#3]
I have successfully built `allsorts-tools` and can run a sample shaping test `./target/debug/allsorts shape -f /path/to/font.ttf -s mlm2 -l MAL "ആരും പേടിക്കണ്ട…പക്ഷേ എല്ലാരും ഓടിക്കോ" | less` and can see the JSON-like output.

It is not easy to verify shaping from this output; is there a possibility to see the actual 'shaped text'? For e.g., the `hb-view` command from `harfbuzz` can output the shaped text in PNG/PDF etc. formats including other forms.

Thanks for any pointers.

**Comment by mikeday** [comment]
We don't have an equivalent tool to hb-view yet, this will require accessing glyph outlines, but in the meantime you can try using Prince (https://www.princexml.com) which now uses Allsorts and generates PDF or PNG files from HTML input.

**Comment by rajeeshknambiar** [comment]
Thanks for the input.

I have downloaded prince, crafted a simple HTML file (added at the end), but results in following error/warning: `prince: page 1: warning: no font for Malayalam character U+0D06, fallback to '?'`.

There seems to be no option to specify font in the `prince --help` options. 

```
<html>
<head>
<meta charset="utf-8">
<style>
    #p1 {font-family: "Rachana Regular",serif;}
</style>
</head>
<body>
<p id="p1">
ആരും പേടിക്കണ്ട…പക്ഷേ എല്ലാരും ഓടിക്കോ
</p>
</body>
</html>
```

**Comment by mikeday** [comment]
On my system the font is just called "Rachana", you can run "fc-list Rachana" on Linux to check. For fonts that are not installed on the system you can use a CSS font-face rule to specify the filename or URL of the font file.

**Comment by rajeeshknambiar** [comment]
Thanks, it was indeed a mistake in the font-family name.

I've been working on a new version of Rachana with rewritten OpenType lookup rules and wanted to make sure that it works well with `allsorts` shaping engine as well. And it indeed works very well!

**Comment by mikeday** [comment]
Thanks, that's great to hear! Trying to get Indic shaping right was a big part of the development.
