### ISSUE TITLE
Subset command error

### ISSUE THREAD

**Issue by LuoZijun** [yeslogic/allsorts-tools#34]
Subset Command:

`$ ./allsorts subset --text "abcdefg" SourceSerif4Variable-Roman.otf d1.otf`

Output:
```
Number of glyphs in new font: 8
Error: subset: parse error: an expected data value was missing
```

[SourceSerif4Variable-Roman.zip](https://github.com/yeslogic/allsorts-tools/files/11581599/SourceSerif4Variable-Roman.zip)

**Comment by wezm** [comment]
Allsorts is failing to parse the font because it's missing a `glyf` table. The name of the font suggests it's a variable font, which isn't supported yet: https://github.com/yeslogic/allsorts/issues/51

**Comment by LuoZijun** [comment]
Thank you for your reply, is there any plan to implement this?

**Comment by mikeday** [comment]
We would like to implement support for variable fonts but it's a big job and not scheduled yet.
